# Generated by Django 2.2.1 on 2019-07-07 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_resumedata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedata',
            name='email',
        ),
        migrations.AddField(
            model_name='resumedata',
            name='email_address',
            field=models.EmailField(max_length=40, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='最大30文字。数字・アルファベット・記号（@/./+/-/_)のみ使えます', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='first_name',
            field=models.CharField(max_length=20, null=True, verbose_name='名前-アルファベット'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='last_name',
            field=models.CharField(max_length=20, null=True, verbose_name='苗字-アルファベット'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='電話番号'),
        ),
    ]
